name: Deploy Stage

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.7.1'
          cache: 'yarn'
          
      - name: Install dependencies
        run: |
          cd character-stage
          yarn install
          
      - name: Build project
        run: |
          cd character-stage
          yarn build
          
      - name: Deploy to Chub.AI
        env:
          CHUB_AUTH_TOKEN: ${{ secrets.CHUB_AUTH_TOKEN }}
        run: |
          echo "Deploying Stage to Chub.AI"
          echo "Auth token length: ${#CHUB_AUTH_TOKEN}"
          # TODO: Implement actual deployment API call
