name: Deploy Stage

on:
  push:
    branches: [main]

jobs:
  deploy:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./character-stage
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.7.1'
          cache: 'yarn'
          cache-dependency-path: 'character-stage/yarn.lock'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Zip dist folder
        run: cd dist && zip -r ../build.zip . && cd ..

      - name: Upload to Chub
        env:
          CHUB_AUTH_TOKEN: ${{ secrets.CHUB_AUTH_TOKEN }}
          STAGE_ID: ${{ secrets.STAGE_ID }}
        run: |
          curl -H "CH-API-KEY: $CHUB_AUTH_TOKEN" -F "file=@build.zip" https://api.chub.ai/extension/${STAGE_ID}/upload
