name: Deploy Stage

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./character-stage
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.7.1'
          cache: 'yarn'
          cache-dependency-path: 'character-stage/yarn.lock'
          
      - name: Install dependencies
        run: yarn install
          
      - name: Build project
        run: yarn build

      - name: Copy built assets into character-stage
        # After building with Vite the output is in the `dist` directory.
        # Copy the compiled files into the root of the `character-stage` folder so that
        # GitHub Pages serves the compiled HTML and assets instead of the source code.
        run: |
          cp -R dist/* .

      - name: Commit and push built site
        # Commit the updated built assets back to the repository. This makes the
        # compiled site available to GitHub Pages on the `main` branch.
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Deploy built character stage to GitHub Pages" || echo "No changes to commit"
          git push
